### ISSUE TITLE
itemCount could be "unrequired"?

### ISSUE THREAD

**Issue by FMorschel** [Limbou/expandable_page_view#40]
This is more of a question than an issue. I have a use-case where I would benefit if I could have an infinite scrolling self-Sizing PageView.

If you look at the actual documentation of [`PageView.builder`](https://api.flutter.dev/flutter/widgets/PageView/PageView.builder.html) you see that the `itemCount` is not `required`. This way, someone parsing the indexes to fit their needed Widgets could create an infinite scrolling view where if you scroll further to the right for example you come back to the first and the other way around as well.

I was wondering what makes `itemCount` required in this case, and if it would be possible to remove this since the initialization is actually using the `PageView.builder` if I'm not istaken.

**Comment by Limbou** [comment]
Hi @FMorschel thank for that question. In the current implementation of ExpandablePageView a list of heights of all children is kept in order to maintain better performance and avoid unnecessary rebuilds. If the `itemCount` was not required, we would have to keep an infinite list, which is of course, not possible. In the future there might be another solution were we just keep a list of N heights closest to the page currently displayed so we can support infinite page views. Let me know if it answers your question.

**Comment by FMorschel** [comment]
It does answer it. Thank you! I'll think for a couple of days and if I can't find any suggestions other than yours to solve this I'll come and close this issue unless you want to close it yourself.

**Comment by Limbou** [comment]
@FMorschel I will close this issue for now. If you come up with any more questions or any potential solutions, please let me know.
