### ISSUE TITLE
Cannot get size from a render object that has not been through layout Exception

### ISSUE THREAD

**Issue by redDwarf03** [Limbou/expandable_page_view#45]
Hello
Thank you for your great Widget !

I met an issue when i want to display a listView with dynamic content

```
SingleChildScrollView(
   child: Column(
      children: [
            ExpandablePageView(
                  children: [
                        T1ListWidget(),
                        T2ListWidget(),
                                  ],
                             ),
                         ],
                     ),
                ),
```

T2ListWidget is a fixed list, no pb
But in the T1ListWidget i have

```

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Expanded(
          child: Padding(
            padding: const EdgeInsets.only(top: 30),
            child: ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              padding: const EdgeInsets.symmetric(vertical: 20),
              itemCount: list.length,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  height: 100,
                  child: displayLign(
                        context,
                        list[index]),
                  );
              },
            ),
          ),
        ),
      ],
    );
  }
```

i obtain the error: 
```Cannot get size from a render object that has not been through layout.```

Thx for help

**Comment by Limbou** [comment]
Hi @redDwarf03 thanks for opening an issue.

The error you see makes perfect sense, as `ListView.builder` only builds its children that are currently visible on the screen, meaning we can never know it's actual size, therefore `ExpandablePageView` doesn't know how much to expand because it doesn't know the size of the `ListView.builder`. This widget can only be used effectively with widgets with a known size, such as a regular `ListView`s. Let me know if you have any additional questions, I will close this issue for now.
